Afilhado4Patas/Models/ViewModels/EmailButtonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Afilhado4Patas.Models.ViewModels
{
    public class EmailButtonViewModel
    {
        public EmailButtonViewModel(string text, string url)
        {
            Text = text;
            Url = url;
        }

        public string Text { get; set; }
        public string Url { get; set; }
    }
}

Afilhado4Patas/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Afilhado4Patas.Data;
using Afilhado4Patas.Models;
using Afilhado4Patas.Models.Estatisticas;
using Afilhado4Patas.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Afilhado4Patas.Controllers.TiposUtilizadores
{
    /// <summary>
    /// Controller que contem todas as ações referentes a funcionalidades que nao requerem sessão iniciada
    /// </summary>
    public class GuestController : Controller
    {
        private readonly ApplicationDbContext _context;

        /// <summary>
        /// Inicialização do controller
        /// </summary>
        /// <param name="context">Objeto da base dados</param>
        public GuestController(ApplicationDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Ação que devolve a view da pagina principal do site
        /// </summary>
        /// <returns>View principal do site</returns>
        public IActionResult Index()
        {
            return View("../Shared/Index");
        }

        /// <summary>
        /// Ação que devolve a view das informações adicionais sobre o site
        /// </summary>
        /// <returns>View do Sobre nós</returns>
        public IActionResult About()
        {
            return View("../Shared/About");
        }

        /// <summary>
        /// Ação que devolve a view com os contactos do nosso site
        /// </summary>
        /// <returns>View dos contactos</returns>
        public IActionResult Contact()
        {
            return View("../Shared/Contact");
        }

        /// <summary>
        /// Ação que devovle a view das adoções
        /// </summary>
        /// <returns>View de adoções</returns>
        public IActionResult Adotar()
        {
            return View("../Shared/Adotar");
        }

        /// <summary>
        /// Ação que devolve a view de doações
        /// </summary>
        /// <returns>View das doações</returns>
        public IActionResult Doar()
        {
            return View("../Shared/Doar");
        }

        /// <summary>
        /// Ação que devolve a view dos animais
        /// </summary>
        /// <returns>View dos animais</returns>
        public IActionResult Animais()
        {
            return View("../Shared/Animais");
        }

        /// <summary>
        /// Ação que devolve a view de ficha de um animal
        /// </summary>
        /// <returns>View da ficha de um animal</returns>
        public IActionResult FichaAnimal(int id)
        {
            Animal animal = _context.Animais.Where(a => a.Id == id).Include(b => b.RacaAnimal).ThenInclude(c => c.CategoriaRaca).FirstOrDefault();
            animal.PorteAnimal = _context.Portes.Where(p => p.Id == animal.PorteId).FirstOrDefault();
            if (animal.Adoptado)
            {
                animal.Adotantes = new List<Utilizadores>();
                foreach(var adotantes in _context.Adotantes.Where(a => a.AnimalId == animal.Id).Include(u => u.Adotante_User).ToList())
                {
                    Utilizadores user = _context.Utilizadores.Where(x => x.PerfilId == adotantes.AdotanteId).FirstOrDefault(); 
                    animal.Adotantes.Add(user);
                }
            }
            return View("../Shared/FichaAnimal", animal);
        }
        
        /// <summary>
        /// Ação que devolve a view de registo no site
        /// </summary>
        /// <returns>View de registo</returns>
        public IActionResult RegistoCompleto()
        {
            return View("../Shared/RegistoCompleto");
        }

        /// <summary>
        /// Ação que efetua o login
        /// </summary>
        /// <returns>View de login</returns>
        public IActionResult RealizarLogin()
        {
            return View();
        }

        /// <summary>
        /// Ação que filtra os animais atraves de certos parametros
        /// </summary>
        /// <param name="items">Filtros da lista de animais</param>
        /// <returns></returns>
        public PartialViewResult AnimaisPorFiltros(int[] items)
        {
            List<Animal> animais = null;
            if (items.Length > 0)
            {
                animais = _context.Animais.Include(p => p.PorteAnimal).Include(r => r.RacaAnimal).ThenInclude(c => c.CategoriaRaca).Where(a => items.ToList().Contains(a.RacaAnimal.CategoriaRaca.Id)).ToList();

            }else
            {
                animais = _context.Animais.Include(p => p.PorteAnimal).Include(r => r.RacaAnimal).ThenInclude(c => c.CategoriaRaca).ToList();
            }
            return PartialView("~/Views/Shared/GridAnimais.cshtml", animais);
        }

        /// <summary>
        /// Ação que devolve a view de erro, caso ocorra um erro esta view e devolvida com a informação do erro
        /// </summary>
        /// <returns>View de erro</returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        /// <summary>
        /// Metodo que devolve os dados para a estatistica dos tipos de animal no sistema
        /// </summary>
        /// <returns>Json com os dados da estatistica</returns>
        [HttpGet]
        public JsonResult PieAnimal()
        {
            DataRetrive dataR = new DataRetrive(_context);
            return Json(dataR.dataGroupTipoAnimais());
        }

        /// <summary>
        /// Metodo que devolve os dados para a estatistica dos utilizadores agrupados por sexo
        /// </summary>
        /// <returns>Json com os dados da estatistica</returns>
        [HttpGet]
        public JsonResult PieMf()
        {
            DataRetrive dataR = new DataRetrive(_context);
            return Json(dataR.dataGroupMF());
        }


    }

}

Afilhado4Patas/Views/Shared/About.cshtml
<div id="seccao_foto_paginaSobre" class="item active">
    <div id="seccao_sobre">
        <h1 id="pagina_titulo">- A Nossa Missão -</h1>
        <p id="p">Ajudar e Salvar o maior número de animais</p>
        <br />
        <br />
        <div id="caixa_texto">
            <p id="p">
                Pretendemos com a nossa plataforma reunir pessoas com animais, facilitando o processo tanto de adoções como apadrinhamentos e dar assim uma vida melhor aos animais que
                passam por nós.
            </p>
        </div>
    </div>
</div>

Afilhado4Patas/Views/Shared/Adotar.cshtml
<div id="seccao_foto_paginaAdotar" class="item active">
    <div id="seccao_adotar">
        <h1 id="pagina_titulo"> Adote Connosco </h1>
        <div id="caixa_texto">
            <p id="p">
                <!--Conheça abaixo os nossos métodos de adoções e também apadrinhamento aos nossos animais-->
                Informe-se em baixo sobre os nossos métodos de adoção e apadrinhamento de animais
            </p>
        </div>
    </div>
</div>
<div id="seccao1">
    <div id="espaco">
        <div id="imagem_titulo">
            <img id="icon_paw" src="~/images/paw white.png" />
            <p id="subtitulo1">Adoção a Tempo Inteiro</p>
        </div>
        <div id="conteudo">
            <p id="paragrafo_white">
                Ganhe um novo membro para a sua família. Vai poder levá-lo para o seu lar, receber o amor que ele tem
                para lhe dar, mas também ser responsável pelo seu sustento e bem estar.
            </p>
            @if (User.IsInRole("Responsavel"))
            {
                <a class="efeito efeito_botao" id="button_white" title="Ver animais" asp-controller="Responsavel" asp-action="Animais">Ver animais</a>
            }
            else if (User.IsInRole("Funcionario"))
            {
                <a class="efeito efeito_botao" id="button_white" title="Ver animais" asp-controller="Funcionario" asp-action="Animais">Ver animais</a>

            }
            else if (User.IsInRole("Utilizador"))
            {
                <a class="efeito efeito_botao" id="button_white" title="Ver animais" asp-controller="Utilizador" asp-action="Animais">Ver animais</a>
            }
            else
            {
                <a class="efeito efeito_botao" id="button_white" title="Ver animais" asp-controller="Guest" asp-action="Animais">Ver animais</a>
            }
        </div>
    </div>
    <img id="imagem_bottom_right_1" src="~/images/foto1.png" />
</div>
<div id="seccao2">
    <div id="espaco">
        <div id="imagem_titulo">
            <img id="icon_paw" src="~/images/paw color.png" />
            <p id="subtitulo2">Adoção Parcial / Apadrinhamento</p>
        </div>
        <div id="conteudo">
            <p id="paragrafo_color">
                Se não pode tê-lo consigo em casa <b>Apadrinhe-o</b>. Poderá visitá-lo, levá-lo consigo em dias
                determinados e proporcionar-lhe outras regalias mediante aprovação da Associação onde ele se encontra.
            </p>
            <p id="paragrafo_color">
                A grande oportunidade é poder tomar conta do seu animal favorito em certos dias, mesmo não podendo
                tê-lo sempre consigo e desta maneira desfrutar do amor dele e ele do seu.
            </p>
            @if (User.IsInRole("Responsavel"))
            {
                <a class="efeito efeito_botao" id="button_red" title="Ver animais" asp-controller="Responsavel" asp-action="Animais">Ver animais</a>
            }
            else if (User.IsInRole("Funcionario"))
            {
                <a class="efeito efeito_botao" id="button_red" title="Ver animais" asp-controller="Funcionario" asp-action="Animais">Ver animais</a>

            }
            else if (User.IsInRole("Utilizador"))
            {
                <a class="efeito efeito_botao" id="button_red" title="Ver animais" asp-controller="Utilizador" asp-action="Animais">Ver animais</a>
            }
            else
            {
                <a class="efeito efeito_botao" id="button_red" title="Ver animais" asp-controller="Guest" asp-action="Animais">Ver animais</a>
            }
        </div>
    </div>
    <img id="imagem_bottom_right_2" src="~/images/foto2.png" />
</div>

Afilhado4Patas/Views/Shared/Contact.cshtml
<div id="seccao_foto_paginaContactos" class="item active">
    <div id="seccao_sobre">
        <h1 id="pagina_titulo">- Contactos -</h1>
        <br />
        <p id="p">Em caso de dúvida não hesite em contactar a nossa equipa em </p>
        <div id="caixa_texto">
            <br />
            <a href="mailto:afilhados4patas@gmail.com">
                <img src="~/images/email.png" width="30px" height="30px" style="margin-right:5px;"/>afilhados4patas@gmail.com
            </a>
        </div>
    </div>
</div>

Afilhado4Patas/Views/Shared/Doar.cshtml
<div id="seccao_foto_paginaDoar" class="item active">
    <div id="seccao_adotar">
        <h1 id="pagina_titulo"> Faça a sua Doação </h1>
        <div id="caixa_texto">
            <p id="p">
                Conheça a baixo os métodos de doações e também voluntariado 
            </p>
        </div>
    </div>
</div>
<div id="seccao_doar">
    <div id="espaco_doar">
        <div id="imagem_doar">
                <img id="icons" src="~/images/dinheiro.png" />
                <p id="descritivo">Dinheiro</p>
        </div>
        <div id="imagem_doar">
                <img id="icons" src="~/images/dog-food-bowl.png" />
                <p id="descritivo">Comida e Mantimentos</p>
        </div>
        <div id="imagem_doar">
                <img id="icons" src="~/images/bandage.png" />
                <p id="descritivo">Primeiros Socorros</p>
        </div>
        <div id="imagem_doar">
                <img id="icons" src="~/images/voluntariado.png" />
                <p id="descritivo">Voluntariado</p>
        </div>
    </div>
</div>

Afilhado4Patas/Views/Shared/FichaAnimal.cshtml
@using Microsoft.AspNetCore.Identity
@using Afilhado4Patas.Data;

@model Afilhado4Patas.Models.Animal

@inject SignInManager<Utilizadores> SignInManager
@inject UserManager<Utilizadores> UserManager
@inject ApplicationDbContext Context
@{
    ViewData["Title"] = "Ficha de Animal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript" src='~/fullcalendar/lib/jquery.min.js'></script>
<script type="text/javascript" src='~/fullcalendar/lib/moment.min.js'></script>
<script type="text/javascript" src='~/fullcalendar/lib/jquery-ui.custom.min.js'></script>
<script type="text/javascript" src='~/fullcalendar/fullcalendar.js'></script>
<script type="text/javascript" src='~/fullcalendar/locale-all.js'></script>
<link rel="stylesheet" href="~/fullcalendar/fullcalendar-custom-fichaAnimal.css" />
<link href="~/fullcalendar/fullcalendar.print.min.css" rel="stylesheet" media="print" />
<link href="~/css/Table/tabela.css" rel="stylesheet" />
<div id="rectangulo_maior"></div>
<div id="page" class="page_maior">
    <div style="height: 120px">
        <div style="float: left; ">
            @{
                if (Model.Foto != null)
                {
                    string src = "/Animais/" + Model.Id + "/" + Model.Foto;
                    <img id="imagem_animal" src="@src" />
                }
                else
                {
                    <img id="imagem_animal" src="~/images/dog-profile.png" />
                }
            }
        </div>
        <div style="float:left; margin-left: 20px">
            <div style="margin-bottom: 5px">
                <p style="color: #fff"><bold>Descrição: </bold></p>
                <p style="color: #fff">@Model.Descricao</p>
            </div>
        </div>
    </div>
    <h3 style="color: #fff">Ficha Animal</h3>
    <div class="table-responsive-vertical shadow-z-1">
        <table id="table" class="table table-hover table-mc-light-blue">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.NomeAnimal)</th>
                    <th>@Html.DisplayNameFor(model => model.DataNasc)</th>
                    <th>@Html.DisplayNameFor(model => model.Sexo)</th>
                    <th>@Html.DisplayNameFor(model => model.Peso) Kg</th>
                    <th>@Html.DisplayNameFor(model => model.PorteId)</th>
                    <th>@Html.DisplayNameFor(model => model.RacaAnimal.CategoriaId)</th>
                    <th>@Html.DisplayNameFor(model => model.RacaId)</th>
                    <th>@Html.DisplayNameFor(model => model.Adoptado)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td data-title="Nome Animal">
                        @Model.NomeAnimal
                    </td>
                    <td data-title="Data Nascimneto">
                        @Model.DataNasc.ToString("dd/MM/yyyy")
                    </td>
                    <td data-title="Sexo">
                        @Model.Sexo
                    </td>
                    <td data-title="Peso">
                        @Model.Peso Kg
                    </td>
                    <td data-title="Porte">
                        @Model.PorteAnimal.TipoPorte
                    </td>
                    <td data-title="Especie">
                        @Model.RacaAnimal.CategoriaRaca.Nome
                    </td>
                    <td data-title="Raca">
                        @Model.RacaAnimal.NomeRaca
                    </td>
                    <td data-title="Adotado">
                        @Html.DisplayFor(model => model.Adoptado)
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div id="centrado_tabela">
        @if (Context.FotosAnimais.Where(i => i.AnimalId == Model.Id).Count() > 0)
        {
            <div class="connected-carousels">
                <div class="stage">
                    <div class="carousel carousel-stage">
                        <ul>
                            @foreach (var foto in Context.FotosAnimais.Where(i => i.AnimalId == Model.Id).ToList())
                            {
                                string src = "/Animais/" + foto.AnimalId + "/Galeria/" + foto.FicheiroNome;
                                <li><img src="@src" width="600" height="400" alt=""></li>
                            }
                        </ul>
                    </div>
                    <a href="#" class="prev prev-stage inactive" data-jcarouselcontrol="true"><span>‹</span></a>
                    <a href="#" class="next next-stage" data-jcarouselcontrol="true"><span>›</span></a>
                </div>

                <div class="navigation">
                    <a href="#" class="prev prev-navigation inactive" data-jcarouselcontrol="true">‹</a>
                    <a href="#" class="next next-navigation" data-jcarouselcontrol="true">›</a>
                    <div class="carousel carousel-navigation">
                        <ul>
                            @foreach (var foto in Context.FotosAnimais.Where(i => i.AnimalId == Model.Id).ToList())
                            {
                                string src = "/Animais/" + foto.AnimalId + "/Galeria/" + foto.FicheiroNome;
                                <li><img src="@src" width="50" height="50" alt=""></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>

    <h3 style="color: slategrey">Atividades</h3>
    <div id="centrado_tabela">
        <div id="calendar"></div>
    </div>


    <script>
        $(document).ready(function () {

            $('#calendar').fullCalendar({
                header: {
                    left: 'prev',
                    center: 'title',
                    right: 'next'
                },
                //defaultDate: '2019-01-12',
                defaultView: 'month',
                navLinks: true, // can click day/week names to navigate views
                editable: true,
                eventLimit: true, // allow "more" link when too many events
                contentHeight: 450,
                apectRatio: 1,
                //themeSystem: 'standard',
                themeSystem: 'bootstrap4',
                locale: 'pt',
                events: "/Funcionario/EventosCalendarioAnimal/@Model.Id"
                /*
                 events: $(function (start, end, timezone, callback)
                {
                $.ajax({
                    dataType: "json",
                    type: "GET",
                    contentType: "application/json; charset=utf-8",
                    url: ,
                    success: function (data) {
                        var events = [];
                        $(data).each(function(i) {
                            events.push({
                                title: $(this).attr('title'),
                                start: $(this).attr('start'),
                                end: $(this).attr('end')
                            })
                        })
                        callback(events);
                    }
            })
            })*/
            });

        });
    </script>






    @if (User.IsInRole("Responsavel"))
    {
        <div class="voltar">
            <a class="efeito efeito_botao_back" id="voltar" asp-controller="Responsavel" asp-action="Animais">Voltar</a>
        </div>
    }
    else if (User.IsInRole("Funcionario"))
    {
        <div class="voltar">
            <a class="efeito efeito_botao_back" id="voltar" asp-controller="Funcionario" asp-action="Animais">Voltar</a>
        </div>
    }
    else if (User.IsInRole("Utilizador"))
    {
        <div class="voltar">
            <a class="efeito efeito_botao_back" id="voltar" asp-controller="Utilizador" asp-action="Animais">Voltar</a>
        </div>
    }
    else
    {
        <div class="voltar">
            <a class="efeito efeito_botao_back" id="voltar" asp-controller="Guest" asp-action="Animais">Voltar</a>
        </div>
    }
</div>

<script>
    $(document).ready(function () {

        var table = $('#table');

        // Table bordered
        $('#table-bordered').change(function () {
            var value = $(this).val();
            table.removeClass('table-bordered').addClass(value);
        });

        // Table striped
        $('#table-striped').change(function () {
            var value = $(this).val();
            table.removeClass('table-striped').addClass(value);
        });

        // Table hover
        $('#table-hover').change(function () {
            var value = $(this).val();
            table.removeClass('table-hover').addClass(value);
        });

        // Table color
        $('#table-color').change(function () {
            var value = $(this).val();
            table.removeClass(/^table-mc-/).addClass(value);
        });
    });

    // jQuery’s hasClass and removeClass on steroids
    // by Nikita Vasilyev
    // https://github.com/NV/jquery-regexp-classes
    (function (removeClass) {

        jQuery.fn.removeClass = function (value) {
            if (value && typeof value.test === "function") {
                for (var i = 0, l = this.length; i < l; i++) {
                    var elem = this[i];
                    if (elem.nodeType === 1 && elem.className) {
                        var classNames = elem.className.split(/\s+/);

                        for (var n = classNames.length; n--;) {
                            if (value.test(classNames[n])) {
                                classNames.splice(n, 1);
                            }
                        }
                        elem.className = jQuery.trim(classNames.join(" "));
                    }
                }
            } else {
                removeClass.call(this, value);
            }
            return this;
        }

    })(jQuery.fn.removeClass);
</script>

Afilhado4Patas/Views/Shared/GridAnimais.cshtml
@model List<Animal>
@using Afilhado4Patas.Data

@inject ApplicationDbContext Context

@do
{
    <div id="container" class="container">
        <div id="row" class="row">
            @{
                var contador = 0;
                foreach (var animal in Model)
                {
                    if (contador < 3)
                    {
                        contador++;
                        Adocao adocaoAnimal = null;
                        //Verificar Animal Adotado
                        @if (animal.Adoptado)
                        {
                            List<Adocao> adocoes = Context.Adocoes.ToList();
                            foreach (var adocao in adocoes)
                            {
                                adocao.Pedido = Context.PedidosAdocao.Where(p => p.Id == adocao.PedidoAdocaoId).FirstOrDefault();
                                if (adocao.Pedido.AnimalId == animal.Id)
                                {
                                    adocaoAnimal = adocao;
                                    break;
                                }
                            }
                        }
                        <div class="animal_item">
                            <div class="product-grid6">
                                <div class="product-image6">
                                    @{
                                        if (animal.Foto != null)
                                        {
                                            string src = "/Animais/" + animal.Id + "/" + animal.Foto;
                                            <img class="pic-1" src="@src" />
                                        }
                                        else
                                        {
                                            <img class="pic-1" src="~/images/dog-profile.png" />
                                        }
                                    }
                                </div>
                                <div class="product-content">
                                    <h3 class="title">@animal.NomeAnimal</h3>
                                    <div>
                                        @animal.Peso Kg
                                        <span>@animal.PorteAnimal.TipoPorte</span>
                                        @animal.Sexo
                                    </div>
                                </div>
                                <ul class="social">
                                    @if (User.IsInRole("Responsavel"))
                                    {
                                        <li>
                                            <a asp-controller="Responsavel" asp-action="FichaAnimal" data-tip="Ver Animal" asp-route-id=@animal.Id>
                                                <i class="fa fa-paw"></i>
                                            </a>
                                        </li>
                                    }
                                    else if (User.IsInRole("Funcionario"))
                                    {
                                        <li>
                                            <a asp-controller="Funcionario" asp-action="FichaAnimal" data-tip="Ver Animal" asp-route-id=@animal.Id>
                                                <i class="fa fa-paw"></i>
                                            </a>
                                        </li>
                                    }
                                    else if (User.IsInRole("Utilizador"))
                                    {
                                        <li>
                                            <a asp-controller="Utilizador" asp-action="FichaAnimal" data-tip="Ver Animal" asp-route-id=@animal.Id>
                                                <i class="fa fa-paw"></i>
                                            </a>
                                        </li>
                                        //Verificar Animal Adotado
                                        @if (animal.Adoptado)
                                        {
                                            //Verificar Adotado ou Apadrinhado
                                            if (adocaoAnimal.Pedido.TipoAdocao == "Parcial")
                                            {
                                                <li>
                                                    <a asp-controller="Utilizador" asp-action="PedidoAdocaoEspecifico" data-tip="Adotar" asp-route-id="@animal.Id">
                                                        <i class="fa fa-heart"></i>
                                                    </a>
                                                </li>
                                            }
                                        }
                                        else
                                        {
                                            <li>
                                                <a asp-controller="Utilizador" asp-action="PedidoAdocaoEspecifico" data-tip="Adotar" asp-route-id="@animal.Id">
                                                    <i class="fa fa-heart"></i>
                                                </a>
                                            </li>
                                        }
                                    }
                                    else
                                    {
                                        <li>
                                            <a asp-controller="Guest" asp-action="FichaAnimal" data-tip="Ver Animal" asp-route-id=@animal.Id>
                                                <i class="fa fa-paw"></i>
                                            </a>
                                        </li>
                                        //Verificar Animal Adotado
                                        @if (animal.Adoptado)
                                        {
                                            //Verificar Adotado ou Apadrinhado
                                            if (adocaoAnimal.Pedido.TipoAdocao == "Parcial")
                                            {
                                                <li>
                                                    <a asp-controller="Guest" asp-action="RealizarLogin" data-tip="Adotar">
                                                        <i class="fa fa-heart"></i>
                                                    </a>
                                                </li>
                                            }
                                        }
                                        else
                                        {
                                            <li>
                                                <a asp-controller="Guest" asp-action="RealizarLogin" data-tip="Adotar">
                                                    <i class="fa fa-heart"></i>
                                                </a>
                                            </li>
                                        }
                                    }
                                </ul>
                                @if (adocaoAnimal != null)
                                {
                                    //Verificar Adotado ou Apadrinhado
                                    if (adocaoAnimal.Pedido.TipoAdocao == "Total")
                                    {
                                        <span class="product-discount-label" style="background-color: #c54b46">Adotado</span>
                                    }
                                    else
                                    {
                                        <span class="product-discount-label" style="background-color: #0081c2">Apadrinhado</span>
                                    }
                                }
                            </div>
                        </div>
                    }
                    else
                    {
                        break;
                    }
                }
                //Remover animais adicionados ao grid
                for (int i = 0; i < contador; i++)
                {
                    Model.Remove(Model[0]);
                }
            }
        </div>
    </div>
} while (Model.Count() > 0);

Afilhado4Patas/Views/Shared/RegistoCompleto.cshtml
<div id="page">
    <div id="centrado">
        <img id="sucesso" src="~/images/sucesso.png" />
        <p>
            Registo feito com sucesso!
        </p>
        <p>
            Para terminar o processo de registo dirija-se ao seu e-mail onde irá receber um e-mail para confirmar a sua conta.
        </p>
    </div>    
</div>